# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/


#exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#highlighter: pygments

highlighter: rouge
